name: php 8.2-zts Fitness Functions
  
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '15 10 * * *' # each day at 10:15 UTC


jobs:
  configured-alpine-is-latest-version:
    name: "Ensure that Alpine is the latest alpine version"
    env:
      LATEST_ALPINE_RELEASE: "3.18.2"    
    runs-on: ubuntu-latest
    steps:
      -  name: Execute
         run: >
             docker run --rm alpine cat /etc/os-release | grep $LATEST_ALPINE_RELEASE

  packages-not-available-on-alpine-for-release-8-2-zts:
    name: Package not available on alpine for php 8.2 zts in edge community, yet
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - phpzts82
          - phpzts82-pecl-redis
          - phpzts82-pecl-memcached
          - phpzts82-pecl-msgpack
          - phpzts82-pecl-imagick
          - phpzts82-pecl-apcu
          - phpzts82-pecl-amqp
          - phpzts82-pecl-protobuf
          - phpzts82-pecl-grpc
          - phpzts82-pecl-pcov
          - phpzts82-pecl-xdebug
    steps:
      -   name: Execute
          run: "! docker run --rm alpine:edge apk --no-cache search ${{ matrix.package }} | grep ${{ matrix.package }}"
